version: 2
project_name: cadenya-config
builds:
  - id: cli
    main: ./cmd/cadenya-config
    binary: cadenya-config
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath, -mod=readonly, -buildvcs=false]
    ldflags:
      - -s -w -X main.version={{ .Version }}
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - id: cli
    ids: [cli]
    formats: [tar.gz]
    name_template: 'cadenya-config_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - NOTICE
      - '*.md'
      - action.yml
      - licenses/*
      - docs/*
      - examples/github-workflow.yaml
      - examples/buildkite.pipeline.yml
      - examples/basic/**
checksum:
  name_template: checksums.txt
snapshot:
  version_template: '{{ .Version }}-snapshot'
changelog:
  sort: asc
release:
  prerelease: auto
  mode: keep-existing
